# dotnet core - build and pack using VersionReaderTask

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  project: 'VersionReaderTaskTest/VersionReaderTaskTest.csproj'

steps:

- task: UseDotNet@2
  displayName: 'Load SDK using 3.1.x'
  inputs:
    version: 3.1.x

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

# tests should go here

#####################################################
# Call VersionReaderTask to set environment variables
#####################################################
- task: VersionReaderTask@2
  displayName: 'Generate build variables'
  inputs:
    searchPattern: '$(project)'
    variablesPrefix: 'DEMO'
    buildPrefix: '.'
#####################################################

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: '$(project)'
    versioningScheme: byEnvVar
    versionEnvVar: 'DEMO_VERSION_BUILD'

# could use 'dotnet push' to push .nupkg here
